version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= # Plex Claim here
    volumes:
      - /home/USERNAME/appdata/plex:/config
      - /home/docker/sonarr/config:/config
      - /media/downloads/tv-sonarr:/tv1
      - /media/downloads2/tv-sonarr:/tv2
      - /media/downloads/radarr:/movies
      - /media/downloads2/radarr:/movies2
    restart: unless-stopped