version: "3"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      WEBUI_PORT: 8080
    volumes:
      - /home/USERNAME/appdata/config:/config
      - /media/downloads/:/downloads
      - /media/downloads/radarr:/movies
      - /media/downloads/tv-sonarr:/tv
    restart: always
