version: '3'

services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - /home/docker/sonarr/config:/config
      - /media/downloads2:/downloads
      - /media/downloads/tv-sonarr:/tv1
      - /media/downloads/tv-sonarr:/tv2