version: '3'

services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/London
    volumes:
      - /home/docker/radarr/config:/config
      - /media/downloads:/downloads
      - /media/downloads/radarr:/movies
      - /media/downloads2/radarr:/movies2
